apiVersion: apps/v1
kind: Deployment
metadata:
  name: doristest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doristest
  template:
    metadata:
      labels:
        app: doristest
    spec:
      containers:
        - name: springboot
          image: dorisfebrianda93/kubernetesjava:TAG
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: dorisservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jhooq-springboot
